<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_ecms_infoclass_shop`;");
E_C("CREATE TABLE `phome_ecms_infoclass_shop` (
  `classid` int(10) unsigned NOT NULL DEFAULT '0',
  `zz_title` text NOT NULL,
  `z_title` varchar(255) NOT NULL DEFAULT '',
  `qz_title` varchar(255) NOT NULL DEFAULT '',
  `save_title` varchar(10) NOT NULL DEFAULT '',
  `zz_titlepic` text NOT NULL,
  `z_titlepic` varchar(255) NOT NULL DEFAULT '',
  `qz_titlepic` varchar(255) NOT NULL DEFAULT '',
  `save_titlepic` varchar(10) NOT NULL DEFAULT '',
  `zz_newstime` text NOT NULL,
  `z_newstime` varchar(255) NOT NULL DEFAULT '',
  `qz_newstime` varchar(255) NOT NULL DEFAULT '',
  `save_newstime` varchar(10) NOT NULL DEFAULT '',
  `zz_productno` text NOT NULL,
  `z_productno` varchar(255) NOT NULL DEFAULT '',
  `qz_productno` varchar(255) NOT NULL DEFAULT '',
  `save_productno` varchar(10) NOT NULL DEFAULT '',
  `zz_materials` text NOT NULL,
  `z_materials` varchar(255) NOT NULL,
  `qz_materials` varchar(255) NOT NULL,
  `save_materials` varchar(10) NOT NULL,
  `zz_intro` text NOT NULL,
  `z_intro` varchar(255) NOT NULL DEFAULT '',
  `qz_intro` varchar(255) NOT NULL DEFAULT '',
  `save_intro` varchar(10) NOT NULL DEFAULT '',
  `zz_dimensions` text NOT NULL,
  `z_dimensions` varchar(255) NOT NULL,
  `qz_dimensions` varchar(255) NOT NULL,
  `save_dimensions` varchar(10) NOT NULL,
  `zz_weight` text NOT NULL,
  `z_weight` varchar(255) NOT NULL DEFAULT '',
  `qz_weight` varchar(255) NOT NULL DEFAULT '',
  `save_weight` varchar(10) NOT NULL DEFAULT '',
  `zz_tprice` text NOT NULL,
  `z_tprice` varchar(255) NOT NULL DEFAULT '',
  `qz_tprice` varchar(255) NOT NULL DEFAULT '',
  `save_tprice` varchar(10) NOT NULL DEFAULT '',
  `zz_price` text NOT NULL,
  `z_price` varchar(255) NOT NULL DEFAULT '',
  `qz_price` varchar(255) NOT NULL DEFAULT '',
  `save_price` varchar(10) NOT NULL DEFAULT '',
  `zz_buyfen` text NOT NULL,
  `z_buyfen` varchar(255) NOT NULL DEFAULT '',
  `qz_buyfen` varchar(255) NOT NULL DEFAULT '',
  `save_buyfen` varchar(10) NOT NULL DEFAULT '',
  `zz_pmaxnum` text NOT NULL,
  `z_pmaxnum` varchar(255) NOT NULL DEFAULT '',
  `qz_pmaxnum` varchar(255) NOT NULL DEFAULT '',
  `save_pmaxnum` varchar(10) NOT NULL DEFAULT '',
  `zz_productpic` text NOT NULL,
  `z_productpic` varchar(255) NOT NULL DEFAULT '',
  `qz_productpic` varchar(255) NOT NULL DEFAULT '',
  `save_productpic` varchar(10) NOT NULL DEFAULT '',
  `zz_newstext` text NOT NULL,
  `z_newstext` varchar(255) NOT NULL DEFAULT '',
  `qz_newstext` varchar(255) NOT NULL DEFAULT '',
  `save_newstext` varchar(10) NOT NULL DEFAULT '',
  `zz_psalenum` text NOT NULL,
  `z_psalenum` varchar(255) NOT NULL DEFAULT '',
  `qz_psalenum` varchar(255) NOT NULL DEFAULT '',
  `save_psalenum` varchar(10) NOT NULL DEFAULT '',
  `zz_pic1` text NOT NULL,
  `z_pic1` varchar(255) NOT NULL,
  `qz_pic1` varchar(255) NOT NULL,
  `save_pic1` varchar(10) NOT NULL,
  `zz_pic2` text NOT NULL,
  `z_pic2` varchar(255) NOT NULL,
  `qz_pic2` varchar(255) NOT NULL,
  `save_pic2` varchar(10) NOT NULL,
  `zz_pic3` text NOT NULL,
  `z_pic3` varchar(255) NOT NULL,
  `qz_pic3` varchar(255) NOT NULL,
  `save_pic3` varchar(10) NOT NULL,
  `zz_other` text NOT NULL,
  `z_other` varchar(255) NOT NULL,
  `qz_other` varchar(255) NOT NULL,
  `save_other` varchar(10) NOT NULL,
  `zz_size` text NOT NULL,
  `z_size` varchar(255) NOT NULL,
  `qz_size` varchar(255) NOT NULL,
  `save_size` varchar(10) NOT NULL,
  `zz_diggtop` text NOT NULL,
  `z_diggtop` varchar(255) NOT NULL,
  `qz_diggtop` varchar(255) NOT NULL,
  `save_diggtop` varchar(10) NOT NULL,
  `zz_cc_color` text NOT NULL,
  `z_cc_color` varchar(255) NOT NULL,
  `qz_cc_color` varchar(255) NOT NULL,
  `save_cc_color` varchar(10) NOT NULL,
  `zz_cc_size` text NOT NULL,
  `z_cc_size` varchar(255) NOT NULL,
  `qz_cc_size` varchar(255) NOT NULL,
  `save_cc_size` varchar(10) NOT NULL,
  PRIMARY KEY (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");

@include("../../inc/footer.php");
?>